{
 "title": "My Dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "Recent Questions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  question,\n  answer,\n  relevance\nFROM requests\nORDER BY timestamp DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Feedback Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "color": { "negative": "#FF0000", "positive": "#32CD32" },
     "rawSql": "SELECT\n  SUM(CASE WHEN feedback  = 1 THEN 1 ELSE 0 END) AS positive,\n  SUM(CASE WHEN feedback = -1 THEN 1 ELSE 0 END) AS negative\nFROM feedback",
     "thresholds": { "negative": { "color": "#FF0000", "value": "negative" }, "positive": { "color": "#32CD32", "value": "positive" } }
    }
   ]
  },
  {
   "title": "Number of requests every hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "Response Time",
     "rawSql": "SELECT\n  timestamp AS time,\n  response_time_in_seconds\nFROM requests\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Relavence Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "color": { "negative": "#FF0000", "neutral": "#F7DC6F", "positive": "#32CD32" },
     "rawSql": "SELECT\n  SUM(CASE WHEN relevance = 'RELEVANT' THEN 1 ELSE 0 END) AS positive,\n  SUM(CASE WHEN relevance = 'PARTLY_RELEVANT' THEN 1 ELSE 0 END) AS neutral,\n  SUM(CASE WHEN relevance = 'NON_RELEVANT' THEN 1 ELSE 0 END) AS negative\nFROM requests",
     "thresholds": { "negative": { "color": "#FF0000" }, "neutral": { "color": "#F7DC6F" }, "positive": { "color": "#32CD32" } }
    }
   ]
  }
 ]
}