name: RAG Care CICD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version here

      - name: Install dependencies
        run: |
          cd services
          pip install -r requirements.txt

      # Run tests using run_tests.py
      - name: Run tests
        run: |
          cd services
          python app/tests/run_tests.py

      # Start Docker services using Docker Compose
      - name: Start Docker services
        run: docker-compose up -d  # Start your services in the background

      # Check if services are up
      - name: Check services status
        run: |
          echo "Waiting for services to be up..."
          for i in {1..10}; do
            if [[ $(docker-compose ps | grep 'Up') ]]; then
              echo "Services are up!"
              break
            fi
            echo "Services are not ready yet. Waiting..."
            sleep 5
          done
          if [[ ! $(docker-compose ps | grep 'Up') ]]; then
            echo "Services did not start in time."
            exit 1
          fi


      # Tear down Docker services after tests
      - name: Tear down Docker services
        run: docker-compose down

